[plugin]
repository = "https://github.com/NadyaNayme/TidyChat.git"
commit = "9e2e3a1bc338e26ae29fef1c6a827d6da5368a6b"
owners = [
    "NadyaNayme",
]
project_path = "TidyChat"
changelog = "Adds new settings for \"smol chat\" and \"normalize specials characters\" under General->Improved Messages"
