[plugin]
repository = "https://github.com/NadyaNayme/TidyChat.git"
commit = "b4a3f0c27730be5d9b80ae98c0923c720c9cfe40"
owners = [
    "NadyaNayme",
]
project_path = "TidyChat"
changelog = "Remove Tippy IPC"
