[plugin]
repository = "https://github.com/NadyaNayme/TidyChat.git"
commit = "80181b6a4dc66e095f1810e6b5a0f5965049b59b"
owners = [
    "NadyaNayme",
]
project_path = "TidyChat"
changelog = "Updated for 6.2"